### ISSUE TITLE
Set up a container registry on ghcr.io

### ISSUE THREAD

**Issue by ivalery111** [libnet/libnet#138]
Set up a container registry on ghcr.io (github) for publishing [docker](https://github.com/libnet/libnet/blob/master/tools/Dockerfile) image.

**Comment by troglobit** [comment]
I have no idea how to test newfangled stuff like vscode[^1], but here's the first try with an automated job to build a container for devs :sunglasses::+1: 

https://github.com/libnet/libnet/pkgs/container/libnet-vscode

So, I'm closing as fixed in [0847bc7](https://github.com/libnet/libnet/commit/0847bc7b2c1d735711b77010760ba8b9b1b9f90f).

[^1]: I'm sticking to Emacs since my brain is too old to learn new keybindings :smile:
