### ISSUE TITLE
GPL license compatibility

### ISSUE THREAD

**Issue by sbouthors** [libnet/libnet#85]
Hi,

After reading this:

- https://www.gnu.org/licenses/license-list.html#OriginalBSD
- https://www.gnu.org/licenses/bsd.html

It seems that I can't use libnet in a GPL project because of this part in the headers:

```
(3) all advertising materials mentioning
  features or use of this software display the following acknowledgement:
  ``This product includes software developed by the University of California,
  Lawrence Berkeley Laboratory and its contributors.
```

Do you agree about it ? 

BRs,
Stephane

**Comment by sam-github** [comment]
Sorry, I don't give license advice, but if you google around, you should be able to find an answer for this question.

Also, we don't own the copyright on libnet, so please don't ask us to change the license.

**Comment by troglobit** [comment]
Reopening to let you guys know I may have found a way around this.  We are looking into changing the license to a more liberal BSD license in the next release! :-)

**Comment by sam-github** [comment]
@troglobit No one person owns copyright, and no contributors have assigned copyright. Without agreement from every single contributor, I'm not sure how a way around this can be found.

**Comment by troglobit** [comment]
I am not a layer, and all that, but practically it usually comes down to the people who have claimed and are listed as copyright holders.  At least that is how I've understood it.  I've talked to Mike, who is the main copyright holder and I'll prepare a pull request this weekend for him and other stakeholders to weigh in on.

I'm aiming for the 2-clause BSD for the pieces of the code that not already have that license header, so not that controversial of a change.

I'm aware it's a potentially big endeavor, and as part of the work I'll try to track down more people who have made (significant) contributions to the main parts of the code base.

**Comment by sam-github** [comment]
I'm not a lawyer either, but I've been working with opensource a long time, and seen many projects face relicensing. I also have undergone multiple license audits during company acquisitions.

Copyright doesn't have to be "claimed", every piece of text long enough to be distinct (single words and numbers _probably_ aren't enough) in the codebase is copyright the author, unless copyright was explicitly assigned, which no one has. This is why many opensource projects have copyright assignment, so they can relicense if they need to. Unless every comitter to a file agrees, or their commits are reversed, anyone doing careful examination of code providence rather than blithely assuming the officially stated copyright is correct would consider a project licensed under *both* A and B simultaneously if it "changed" its license from A to B without evidence all copyright holders agreed.

To be clear, I am willing to relicense anything I've done as long as it is to a reasonable opensource license.

I've not reviewed how many distinct comitters there are, maybe its only a handful, and it'll be easy to get their sign-off. I watch with interest!

**Comment by troglobit** [comment]
Great feedback, thank you!  I realize this could take some time, but most of the code base is already more than OK, licensed under the 2-clause BSD.  I want to make an effort at tackling the `libnet_link_*.c` files, and the ASN.1 code.  The former are 4-clause BSD, which like @sbouthors points out, is a bit hairy to deal with.  So if we (I) could get our major contributors to those files to agree to moving to the 2-clause, or at least the 3-clause, it would be a huge win.  

I'll put together a pull request during the weekend where we can continue the discussion :)

**Comment by sbouthors** [comment]
Hey, great to hear that. I don't have experience about relicensing add I will follow how is going the merge request. In case of success it should give more users.

**Comment by sam-github** [comment]
> I can't use libnet in a GPL project because of this part in the headers:

@sbouthors This is a classic problem for GPL code using OpenSSL, probably fixable the same way: 
https://opensource.stackexchange.com/questions/2233/gpl-v3-with-openssl-exception

**Comment by troglobit** [comment]
Advertising clause dropped in merge commit 69545446d5383bb406034c267c963274436e147a, for upcoming v1.3.

**Comment by sbouthors** [comment]
Thanks !
